### ISSUE TITLE
deleteMany({}): too many mutations 

### ISSUE THREAD

**Issue by waptik** [skoshx/pentagon#28]
So i have a test model where i generated 70 items. I was trying to clean it up but it was possible because i keep hitting this error `too many mutations`.
Here's how i'm deleting all items
```ts
  await pentagon.TestTerms.deleteMany({});
````

And full error logs in terminal
![image](https://github.com/skoshx/pentagon/assets/1687551/27108b0b-5120-4d6b-8f8c-e54ef73d66f1)

**Comment by skoshx** [comment]
Hello, and thanks for opening this issue! Seems like we always do cleanup using the raw `kv.list` and `kv.delete` so we have completely missed this, apologies for that!

Have made a reproduction and will look into this ASAP! :)

**Comment by waptik** [comment]
> Hello, and thanks for opening this issue! Seems like we always do cleanup using the raw `kv.list` and `kv.delete` so we have completely missed this, apologies for that!
> 
> Have made a reproduction and will look into this ASAP! :)

Okay sure, looking forward to the fix.

**Comment by waptik** [comment]
I'm facing some having some other issues.
One is related to #26.
![image](https://github.com/skoshx/pentagon/assets/1687551/ea6087b3-993f-4c70-bd13-132726661c08)

=======================================================

And the other is related `.create()` and `.findFirst()` and `.findMany()`
With `.create()`, the item is created but it somehow looks like it doesn't exist. I'm getting `undefined` when searching for a single item and `[]` for all items
![image](https://github.com/skoshx/pentagon/assets/1687551/fb82411e-d914-4a5c-afdb-2de25016cb09)
![image](https://github.com/skoshx/pentagon/assets/1687551/515669b8-b977-4bac-8a85-8255ce0b86b6)

Here's the models definition:
```ts

const WithDefautTimestamps = z.object({
  createdAt: z
    .string()
    .datetime()
    .default(() => new Date().toISOString()),
  updatedAt: z
    .string()
    .datetime()
    .default(() => new Date().toISOString())
    .nullable()
    .nullable(),
});


export const Meeting = z.object({
  title: z.string(),
  description: z.string(),
  userId: z.number(),
});


export const BookingReference = z
  .object({
    id: z
      .string()
      .uuid()
      .describe("primary")
      .default(() => generateUUID()),
    type: z.string().min(1),
    bookingId: z.string().uuid().optional(),
    meetingId: z.string().uuid().optional(),
    meetingUrl: z.string().url().optional(),
    meetingPassword: z.string().optional(),
  })
  .merge(WithDefautTimestamps);
```

Now here is the client definition:
```ts
export const pentagon = createPentagon(kv, {
  
  bookingReference: {
    schema: BookingReference,
  },
  meeting: {
    schema: Meeting,
  },
});
```

**Comment by skoshx** [comment]
@waptik Sorry to hear that, I will need to put a lot of work on the test suite it seems! 

Just by looking at your `Meeting` schema, it looks like it doesn't have a primary key (eg. `id: z.string().uuid().describe('primary')` which might be the reason it cannot create the indexes correctly (might be a bug, not sure if we want to make it mandatory to have a primary key.)

Might it fix the problem if you add a primary key?

**Comment by skoshx** [comment]
@waptik 

I pushed a fix to this issue now. Let me know if adding the primary key to the schema fixes your problems, and if it does, I can release a minor version with this fix! :)

**Comment by waptik** [comment]
> 6b9f262

This was my initial version which didn't work before reducing it to what i posted here
```ts
export const Meeting = z
  .object({
    id: z
      .string()
      .uuid()
      .describe("primary")
      .default(() => generateUUID()),
    title: z.string(),
    description: z.string(),
    slug: z
      .string()
      .describe("unique")
      .min(1)
      .default(() => generateShortId()),
    duration: z.number().min(1),
    price: z.number().min(5),
    // relations
    userId: z.number(),
  })
  .merge(WithDefautTimestamps);
```

Weirdly enough, this works but that where i found the `.deleteMany({})` bug
```ts

export const AgreedTerms = z
  .object({
    id: z.number().describe("primary"),
  })
  .merge(WithDefautTimestamps);
```

**Comment by waptik** [comment]
> @waptik
> 
> I pushed a fix to this issue now. Let me know if adding the primary key to the schema fixes your problems, and if it does, I can release a minor version with this fix! :)

Worderful! No more error when using `.deleteMany` and items get deleted too

**Comment by waptik** [comment]
@skoshx I am still getting empty items when using `.findMany` or `findFirst` after creating a new item.
```ts

export const BookingReference = z
  .object({
    id: z
      .string()
      .uuid()
      .describe("primary")
      .default(() => generateUUID()),
    type: z.string().min(1),
    bookingId: z.string().uuid().optional(),
    meetingId: z.string().uuid().optional(),
    meetingUrl: z.string().url().optional(),
    meetingPassword: z.string().optional(),
  })
  .merge(WithDefautTimestamps);
````
![image](https://github.com/skoshx/pentagon/assets/1687551/4184d322-b4b4-4d17-ba1d-77650b24f1f5)

**Comment by skoshx** [comment]
@waptik Ok, thanks for letting me know! Could you open a new issue with the minimal reproduction steps, that would help me out a lot! :)

**Comment by waptik** [comment]
> @waptik Ok, thanks for letting me know! Could you open a new issue with the minimal reproduction steps, that would help me out a lot! :)

Yeah sure, I'll do that tomorrow. 
Thanks for your help 🙏🏾
